### ISSUE TITLE
Release patch

### ISSUE THREAD

**Issue by dcousens** [JedWatson/touchstonejs-tasks#10]
@JedWatson please publish a patch.

https://github.com/touchstonejs/touchstonejs-tasks/commit/454e0998885bde20f187aa948c3dfb8fecd2b555

The less stream is more stateful than I expected,  causing this to previously explode about writing after the stream ended.

To resolve this,  I moved the stream instantiation back into the closure.

Its a bit lame,  but,  its clear.

**Comment by JedWatson** [comment]
Done
