### ISSUE TITLE
Include static css files in build process

### ISSUE THREAD

**Issue by nikos** [JedWatson/touchstonejs-tasks#14]
Beside the app.less plumbing, it would be helpful if also static CSS files would be copied into the target www directory on build time. It would probably also not hurt watching for changes on this directory.

**Comment by nikos** [comment]
@dcousens @JedWatson with #15 being merged into master now, could you please push a new version of touchstonejs-tasks to the npm registry, thanks!

**Comment by JedWatson** [comment]
Sorry for the delay @nikos - I totally missed the notification on this one :(

Publishing a new version today
