### ISSUE TITLE
Put all modules bundle.js

### ISSUE THREAD

**Issue by pke** [JedWatson/touchstonejs-tasks#17]
It would make sense, to put every code that comes out of `node_modules` into one `bundle.js` file cause they do not change. Much like `react.js` is created atm. Only components under `src` are bundled in `app.js` which should be much faster to compile.

**Comment by JedWatson** [comment]
it's hard to get that happening automatically but I'll add all the common ones that touchstone uses to the list for the release I'm preparing.
