### ISSUE TITLE
Use gulp-connect?

### ISSUE THREAD

**Issue by dcousens** [JedWatson/touchstonejs-tasks#8]
https://www.npmjs.com/package/gulp-connect

Any reason we can't use this like in https://github.com/touchstonejs/touchstonejs ?

**Comment by JedWatson** [comment]
Should be fine

Express was originally used so apps could be easily hosted on remote servers for preview builds (e.g Heroku)

So before these tasks were extracted, that was shared

Makes sense to use gulp-connect and live reload, and I don't think there's still a need to consolidate this. If we want to publish a preview server for a touchstone app that can be handled elsewhere...

Thoguhts?
